language: node_js

node_js:
  - "stable"

script:
  - npm test
  - npm run report-coverage

after_script: 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage